### ISSUE TITLE
motherboard GA-H61M-DS2H CPU Intel(R) Pentium(R) CPU G2030 @ 3.00GHz

### ISSUE THREAD

**Issue by gilaranuji** [DriverPackSolution/DriverPack-Solution#39]
error to instal 9 drivers of intel corporation (7 intel 6 series/c200 and 1 xeon processor more one h61 express chipset.
![drperror01](https://cloud.githubusercontent.com/assets/10861778/6056291/bc7a485c-acf5-11e4-9293-cacbe52ea4cf.png)
Simply, the installation starts and nothing happens ... after a while asks to close the program due to an error.

**Comment by DmitryPakhomov** [comment]
This bug is fixed.
