### ISSUE TITLE
error 0x8007042c/windowupdate

### ISSUE THREAD

**Issue by Jatutu75** [DriverPackSolution/DriverPack-Solution#45]

**Comment by Jatutu75** [comment]
I tried to update window but error message popup 0x8007042c

**Comment by Jatutu75** [comment]
what can I do to fix it. Please help

**Comment by gimntut** [comment]
Article: https://support.microsoft.com/en-us/kb/2530126/en-us
Direct link to fix tool: http://go.microsoft.com/?linkid=9810866
