### ISSUE TITLE
Сволочи! зачем оперу и елементи яндекса пихаете?

### ISSUE THREAD

**Issue by 6pm** [DriverPackSolution/DriverPack-Solution#52]
После установки драйверов обнаружил 4 лишние программи - яндекс -елементи, опера, фоксит ридер и ю-торрент. Зачем ви так делаете сволочи?

**Comment by slvxstar** [comment]
Это для таких как ти, неспособных убрать галочку.

**Comment by 6pm** [comment]
галочку запрятали, специально сделали так чтоб не нажимали! ублюдки!
у меня синий екран после ваших драйверов вилетал
