### ISSUE TITLE
DRP 15.7 и 15.8: старые драйвера на Intel HD Graphics 4000 (Win 7 SP1 x64)

### ISSUE THREAD

**Issue by reporter191** [DriverPackSolution/DriverPack-Solution#59]
После установки всех драйверов из драйверпака (и пары перезагрузок) запускаю интеловскую программу Driver Update Utility - https://downloadcenter.intel.com/download/24345/Intel-Driver-Update-Utility . И сразу оказалось, что драйверпаком был установлен весьма старый драйвер 9 версии, в то время как можно обновиться до 15 версии! Эта интеловская утилита автоматически нашла и скачала новый драйвер куда-то в Downloads , и успешно обновилась с него

**Comment by reporter191** [comment]
Я решил выложить этот более новый драйвер (для Win 7 SP1 x64), чтобы возможно вы интегрировали его в Ваш драйверпак. http://www.datafilehost.com/d/5b6e703c (перед тем как нажимать серую кнопку "Download", пожалуйста не забудьте снять галочку возле текста под ней - "Use our download manager and get recommended downloads"

**Comment by SamLab** [comment]
вы скачали месячную версию 15.8 со старыми драйверами - в еженедельных обновлениях этот драйвер уже добавлен и в начале сентября в очередном месячном обновлении 15.9 он будет
