### ISSUE TITLE
DRP 15.8: не помешало бы обновить драйвера NVIDIA GT 640M для Win 7 SP1 x64

### ISSUE THREAD

**Issue by reporter191** [DriverPackSolution/DriverPack-Solution#60]
Драйвера NVIDIA в Вашем драйверпаке тоже устарели, пусть и не так сильно как интеловские (про них см. Issue #59 ) Пожалуйста, скачайте новую версию драйверов GT 640M с официального сайта NVIDIA и интегрируйте её в Ваш драйверпак: http://uk.download.nvidia.com/Windows/355.60/355.60-notebook-win8-win7-64bit-international-whql.exe

**Comment by SamLab** [comment]
вы скачали месячную версию 15.8 со старыми драйверами - в еженедельных обновлениях этот драйвер уже добавлен и в начале сентября в очередном месячном обновлении 15.9 он будет
