### ISSUE TITLE
Независимая установка драйверов и софта от закачки

### ISSUE THREAD

**Issue by who0ps** [DriverPackSolution/DriverPack-Solution#68]
На данный момент схема такая: скачались все - установились все. То есть установка не начинается до полной закачки последнего файла.

Предлагаю сделать установку файлов независимой от закачки, но по наличии загруженных файлов.
Закачался первый файл - одновременно началась установка первого и закачка уже второго файла. 

Заметно ускорит общий процесс.

**Comment by artxgroup** [comment]
Спасибо за предложение! На этой неделе уже релизим "Умную установку", это практически тоже самое, что вы описали, только с большим числом зависимостей.

**Comment by who0ps** [comment]
Вроде работает.
